name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bank-rest-api:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bank-rest-api:latest


  deploy:
    needs: build
    runs-on: [self-hosted, aws-ec2]

    steps:
      - name: Login to Docker Hub (EC2)
        run: echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull latest image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/bank-rest-api:latest

      - name: Remove old container (ignore errors)
        run: sudo docker rm -f springboot-example-container || true

      - name: Run new container
        run: |
          sudo docker run -d \
            -p 8080:8080 \
            --name springboot-example-container \
            ${{ secrets.DOCKER_USERNAME }}/bank-rest-api:latest
